### ISSUE TITLE
Acquire an avatar for the project

### ISSUE THREAD

**Issue by SEbbaDK** [SEbbaDK/sonica#26]
Since much of the project had been personified as Sonica and responds in a cutesy way, it would be great to have a cute avatar to go along with the project.

**Comment by SEbbaDK** [comment]
This might possible be something for @NastyLad

**Comment by Rawrior** [comment]
![image](https://user-images.githubusercontent.com/9444082/137258327-dbbd20bc-d490-4031-ac49-f169d208c7b8.png)

**Comment by SEbbaDK** [comment]
> Are there any specifications on what people want for an avatar? I can conjure something up, but I reckon people have an idea of what they want?

I think something in the same mood as what is used in the current thumbnail is good, but i agree with @Rawrior, headphones would fit well
