### ISSUE TITLE
Separate command invocation and command logic

### ISSUE THREAD

**Issue by Rawrior** [SEbbaDK/sonica#33]
This sorta ties into #28 

Separating the command invocation and command logic would make it infinitely easier to test everything. This will in turn will make it easier to change and/or add and/or remove things.

**Comment by Rawrior** [comment]
Something like that. As an example, the functionality of shuffle would be changed from something like

```python
@bot.command(name = 'shuffleall')
async def shuffleall(ctx):
    playlist.shuffleall()
    return await ctx.message.channel.send("Queue and backlog shuffled!")
```
It could be something along the lines of
```python
from bot_functionality import shuffleall

# ...

@bot.command(name = 'shuffleall')
async def invoke_shuffleall(ctx):
    return await ctx.message.channel.send(shuffleall())
```

Testing could then work on just the `bot_functionality` module, which should hopefully be easier to test and give mocks.

**Comment by SEbbaDK** [comment]
This is now forced through #34
